### ISSUE TITLE
Important: Consistency in styling

### ISSUE THREAD

**Issue by blerude** [Kerrie-jr/prj-rev-bwfs-dasmoto#2]
https://github.com/Kerrie-jr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L10

Because you use classes in the rest of your stylings, you should do so here instead of just writing the styles into the tag.

**Comment by Kerrie-jr** [comment]
Yes, I actually tried to do this.  Unfortunately I was coding the style sheet as if were in the same position as the index.html.  My only recourse then was to link to it on it's home website - I didn't want to do that since it wasn't really using the content in our Resources folder.  I've corrected this and combined the text styling with the background image for a single line of code.
